### ISSUE TITLE
1.18.2 Crash on player connect

### ISSUE THREAD

**Issue by ghost** [LukeGrahamLandryMC/travel_anchors#2]
```
[21:53:57] [Server thread/INFO]: hellishinc[/24.19.4.177:59748] logged in with entity id 1 at (4.5, 85.0, -3.5)
[21:53:57] [Server thread/INFO]: Syncing config to hellishinc (9881db7d-8d9a-4a83-8786-ab79cdd561ec)
[21:53:57] [Server thread/INFO]: Sent REI Loot info to hellishinc
[21:53:57] [Server thread/ERROR]: Encountered an unexpected exception
java.util.ServiceConfigurationError: ca.lukegrahamlandry.travelstaff.platform.services.IPlatformHelper: ca.lukegrahamlandry.travelstaff.platform.FabricPlatformHelper Unable to get public no-arg constructor
	at java.util.ServiceLoader.fail(ServiceLoader.java:586) ~[?:?]
	at java.util.ServiceLoader.getConstructor(ServiceLoader.java:679) ~[?:?]
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1240) ~[?:?]
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273) ~[?:?]
	at java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309) ~[?:?]
	at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393) ~[?:?]
	at java.util.ServiceLoader.findFirst(ServiceLoader.java:1811) ~[?:?]
	at ca.lukegrahamlandry.travelstaff.platform.Services.load(Services.java:19) ~[Staff%20of%20Travelling-fabric-1.18.2-1.07.jar:?]
	at ca.lukegrahamlandry.travelstaff.platform.Services.<clinit>(Services.java:12) ~[Staff%20of%20Travelling-fabric-1.18.2-1.07.jar:?]
	at ca.lukegrahamlandry.travelstaff.FabricEventListener.onJoin(FabricEventListener.java:39) ~[Staff%20of%20Travelling-fabric-1.18.2-1.07.jar:?]
	at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$2(ServerPlayConnectionEvents.java:48) ~[fabric-networking-api-v1-1.0.22+e6b169eb60-134892b2de16cba2.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:65) ~[fabric-networking-api-v1-1.0.22+e6b169eb60-134892b2de16cba2.jar:?]
	at net.minecraft.class_3324.handler$eac000$handlePlayerConnection(class_3324.java:7964) ~[server-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:192) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_33800(class_3248.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_14384(class_3248.java:117) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.redirect$ead000$handlePlayerJoin(class_3248.java:563) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_18785(class_3248.java:67) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:243) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:918) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:322) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bnp000$modifiedRunLoop(MinecraftServer.java:6396) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_1921
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3405) ~[?:?]
	at java.lang.Class.getConstructor0(Class.java:3610) ~[?:?]
	at java.lang.Class.getConstructor(Class.java:2303) ~[?:?]
	at java.util.ServiceLoader$1.run(ServiceLoader.java:666) ~[?:?]
	at java.util.ServiceLoader$1.run(ServiceLoader.java:663) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
	at java.util.ServiceLoader.getConstructor(ServiceLoader.java:674) ~[?:?]
	... 25 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_1921
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3405) ~[?:?]
	at java.lang.Class.getConstructor0(Class.java:3610) ~[?:?]
	at java.lang.Class.getConstructor(Class.java:2303) ~[?:?]
	at java.util.ServiceLoader$1.run(ServiceLoader.java:666) ~[?:?]
	at java.util.ServiceLoader$1.run(ServiceLoader.java:663) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
	at java.util.ServiceLoader.getConstructor(ServiceLoader.java:674) ~[?:?]
	... 25 more
```

Full log: https://mclo.gs/he8N4nl

Sidenote - I hate whoever is doing the stupid log spam "art".

**Comment by LukeGrahamLandry** [comment]
another silly mistake
life is hard

**Comment by Saereth** [comment]
Similarly for 1.19 as well
https://www.toptal.com/developers/hastebin/ruqinolovu.rb

**Comment by Saereth** [comment]
https://www.toptal.com/developers/hastebin/ruqinolovu.rb 1.19 as well
